language: go

env:
  - GO15VENDOREXPERIMENT=1

before_install:
  - docker run --name cassandra -d --net=host cassandra:3.5
  - wget https://archive.apache.org/dist/kafka/0.8.2.1/kafka_2.10-0.8.2.1.tgz
  - tar -xzf kafka_2.10-0.8.2.1.tgz
  - cd kafka_2.10-0.8.2.1
  - bin/zookeeper-server-start.sh config/zookeeper.properties &
  - bin/kafka-server-start.sh config/server.properties &
  - cd ..

install:
  - go get github.com/Masterminds/glide
  - go build

go:
  - 1.5
  - 1.6
  - tip

script: go test $(glide novendor)
